title: Name Lastname # your name (or website title) here
logo: "/images/Alba Skeja.jpeg?raw=true" # your photo (or logo) here


description: > 
  About Me:<br><br>
  brief explanation.
  what you od
  <br><br>
  * profession 1  
  <br><br>
  * profession 2  
  <br><br>
  Connect with Me:<br><br>
  <a href="https://www.linkedin.com/in/albana-skeja-24as/">View My LinkedIn Profile</a> 
  <br><br>

  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-VL2TWQ1HK6 # your Google Analytics tracking ID here 10350835511         UA-000000-0
